apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
